/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as DisclaimerRouteImport } from './routes/disclaimer'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedVerifyRouteImport } from './routes/_authenticated/verify'
import { Route as AuthenticatedProfileRouteImport } from './routes/_authenticated/profile'
import { Route as AuthenticatedLearnRouteImport } from './routes/_authenticated/learn'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedAchievementsRouteImport } from './routes/_authenticated/achievements'
import { Route as AuthenticatedVerifyIdRouteImport } from './routes/_authenticated/verify_.$id'
import { Route as AuthenticatedTrustReplayIdRouteImport } from './routes/_authenticated/trust-replay.$id'
import { Route as AuthenticatedQuizModuleIdRouteImport } from './routes/_authenticated/quiz.$moduleId'
import { Route as AuthenticatedLearnSlugRouteImport } from './routes/_authenticated/learn_.$slug'

const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const DisclaimerRoute = DisclaimerRouteImport.update({
  id: '/disclaimer',
  path: '/disclaimer',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedVerifyRoute = AuthenticatedVerifyRouteImport.update({
  id: '/verify',
  path: '/verify',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedProfileRoute = AuthenticatedProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedLearnRoute = AuthenticatedLearnRouteImport.update({
  id: '/learn',
  path: '/learn',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAchievementsRoute =
  AuthenticatedAchievementsRouteImport.update({
    id: '/achievements',
    path: '/achievements',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedVerifyIdRoute = AuthenticatedVerifyIdRouteImport.update({
  id: '/verify_/$id',
  path: '/verify/$id',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedTrustReplayIdRoute =
  AuthenticatedTrustReplayIdRouteImport.update({
    id: '/trust-replay/$id',
    path: '/trust-replay/$id',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedQuizModuleIdRoute =
  AuthenticatedQuizModuleIdRouteImport.update({
    id: '/quiz/$moduleId',
    path: '/quiz/$moduleId',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedLearnSlugRoute = AuthenticatedLearnSlugRouteImport.update({
  id: '/learn_/$slug',
  path: '/learn/$slug',
  getParentRoute: () => AuthenticatedRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/contact': typeof ContactRoute
  '/disclaimer': typeof DisclaimerRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/privacy': typeof PrivacyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/terms': typeof TermsRoute
  '/achievements': typeof AuthenticatedAchievementsRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/learn': typeof AuthenticatedLearnRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/verify': typeof AuthenticatedVerifyRoute
  '/learn/$slug': typeof AuthenticatedLearnSlugRoute
  '/quiz/$moduleId': typeof AuthenticatedQuizModuleIdRoute
  '/trust-replay/$id': typeof AuthenticatedTrustReplayIdRoute
  '/verify/$id': typeof AuthenticatedVerifyIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/contact': typeof ContactRoute
  '/disclaimer': typeof DisclaimerRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/privacy': typeof PrivacyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/terms': typeof TermsRoute
  '/achievements': typeof AuthenticatedAchievementsRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/learn': typeof AuthenticatedLearnRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/verify': typeof AuthenticatedVerifyRoute
  '/learn/$slug': typeof AuthenticatedLearnSlugRoute
  '/quiz/$moduleId': typeof AuthenticatedQuizModuleIdRoute
  '/trust-replay/$id': typeof AuthenticatedTrustReplayIdRoute
  '/verify/$id': typeof AuthenticatedVerifyIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/about': typeof AboutRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/contact': typeof ContactRoute
  '/disclaimer': typeof DisclaimerRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/privacy': typeof PrivacyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/terms': typeof TermsRoute
  '/_authenticated/achievements': typeof AuthenticatedAchievementsRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/learn': typeof AuthenticatedLearnRoute
  '/_authenticated/profile': typeof AuthenticatedProfileRoute
  '/_authenticated/verify': typeof AuthenticatedVerifyRoute
  '/_authenticated/learn_/$slug': typeof AuthenticatedLearnSlugRoute
  '/_authenticated/quiz/$moduleId': typeof AuthenticatedQuizModuleIdRoute
  '/_authenticated/trust-replay/$id': typeof AuthenticatedTrustReplayIdRoute
  '/_authenticated/verify_/$id': typeof AuthenticatedVerifyIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/admin'
    | '/auth'
    | '/contact'
    | '/disclaimer'
    | '/forgot-password'
    | '/privacy'
    | '/reset-password'
    | '/terms'
    | '/achievements'
    | '/dashboard'
    | '/learn'
    | '/profile'
    | '/verify'
    | '/learn/$slug'
    | '/quiz/$moduleId'
    | '/trust-replay/$id'
    | '/verify/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/admin'
    | '/auth'
    | '/contact'
    | '/disclaimer'
    | '/forgot-password'
    | '/privacy'
    | '/reset-password'
    | '/terms'
    | '/achievements'
    | '/dashboard'
    | '/learn'
    | '/profile'
    | '/verify'
    | '/learn/$slug'
    | '/quiz/$moduleId'
    | '/trust-replay/$id'
    | '/verify/$id'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/about'
    | '/admin'
    | '/auth'
    | '/contact'
    | '/disclaimer'
    | '/forgot-password'
    | '/privacy'
    | '/reset-password'
    | '/terms'
    | '/_authenticated/achievements'
    | '/_authenticated/dashboard'
    | '/_authenticated/learn'
    | '/_authenticated/profile'
    | '/_authenticated/verify'
    | '/_authenticated/learn_/$slug'
    | '/_authenticated/quiz/$moduleId'
    | '/_authenticated/trust-replay/$id'
    | '/_authenticated/verify_/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  AboutRoute: typeof AboutRoute
  AdminRoute: typeof AdminRoute
  AuthRoute: typeof AuthRoute
  ContactRoute: typeof ContactRoute
  DisclaimerRoute: typeof DisclaimerRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  PrivacyRoute: typeof PrivacyRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  TermsRoute: typeof TermsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/disclaimer': {
      id: '/disclaimer'
      path: '/disclaimer'
      fullPath: '/disclaimer'
      preLoaderRoute: typeof DisclaimerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/verify': {
      id: '/_authenticated/verify'
      path: '/verify'
      fullPath: '/verify'
      preLoaderRoute: typeof AuthenticatedVerifyRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/profile': {
      id: '/_authenticated/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthenticatedProfileRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/learn': {
      id: '/_authenticated/learn'
      path: '/learn'
      fullPath: '/learn'
      preLoaderRoute: typeof AuthenticatedLearnRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/achievements': {
      id: '/_authenticated/achievements'
      path: '/achievements'
      fullPath: '/achievements'
      preLoaderRoute: typeof AuthenticatedAchievementsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/verify_/$id': {
      id: '/_authenticated/verify_/$id'
      path: '/verify/$id'
      fullPath: '/verify/$id'
      preLoaderRoute: typeof AuthenticatedVerifyIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/trust-replay/$id': {
      id: '/_authenticated/trust-replay/$id'
      path: '/trust-replay/$id'
      fullPath: '/trust-replay/$id'
      preLoaderRoute: typeof AuthenticatedTrustReplayIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/quiz/$moduleId': {
      id: '/_authenticated/quiz/$moduleId'
      path: '/quiz/$moduleId'
      fullPath: '/quiz/$moduleId'
      preLoaderRoute: typeof AuthenticatedQuizModuleIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/learn_/$slug': {
      id: '/_authenticated/learn_/$slug'
      path: '/learn/$slug'
      fullPath: '/learn/$slug'
      preLoaderRoute: typeof AuthenticatedLearnSlugRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedAchievementsRoute: typeof AuthenticatedAchievementsRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedLearnRoute: typeof AuthenticatedLearnRoute
  AuthenticatedProfileRoute: typeof AuthenticatedProfileRoute
  AuthenticatedVerifyRoute: typeof AuthenticatedVerifyRoute
  AuthenticatedLearnSlugRoute: typeof AuthenticatedLearnSlugRoute
  AuthenticatedQuizModuleIdRoute: typeof AuthenticatedQuizModuleIdRoute
  AuthenticatedTrustReplayIdRoute: typeof AuthenticatedTrustReplayIdRoute
  AuthenticatedVerifyIdRoute: typeof AuthenticatedVerifyIdRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAchievementsRoute: AuthenticatedAchievementsRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedLearnRoute: AuthenticatedLearnRoute,
  AuthenticatedProfileRoute: AuthenticatedProfileRoute,
  AuthenticatedVerifyRoute: AuthenticatedVerifyRoute,
  AuthenticatedLearnSlugRoute: AuthenticatedLearnSlugRoute,
  AuthenticatedQuizModuleIdRoute: AuthenticatedQuizModuleIdRoute,
  AuthenticatedTrustReplayIdRoute: AuthenticatedTrustReplayIdRoute,
  AuthenticatedVerifyIdRoute: AuthenticatedVerifyIdRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  AboutRoute: AboutRoute,
  AdminRoute: AdminRoute,
  AuthRoute: AuthRoute,
  ContactRoute: ContactRoute,
  DisclaimerRoute: DisclaimerRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  PrivacyRoute: PrivacyRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  TermsRoute: TermsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
